server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/agri_db?currentSchema=inventory_schema
    username: admin
    password: admin

  redis:
    host: redis
    port: admin
    password: 123456
    lock-prefix: inventory-lock: