server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/agri_db?currentSchema=order_schema
    username: admin
    password: admin

  redis:
    host: redis
    port: 6379
    password: 123456

  rabbitmq:  # hoặc kafka nếu bạn dùng
    host: rabbitmq
    port: 5672