server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agri_db?currentSchema=user_schema
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: user_schema
    baseline-on-migrate: true

keycloak:
  realm: agri-realm
  auth-server-url: http://keycloak:9090
  resource: user-service-client
  bearer-only: true
  ssl-required: external
  use-resource-role-mappings: true

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: 12345678
  bucket: user-images