-- 1. Tạo Schema riêng để tách biệt dữ liệu
CREATE SCHEMA IF NOT EXISTS inventory_service;

-- 2. Tạo bảng inventories
CREATE TABLE inventory_service.inventories
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        VARCHAR(50) NOT NULL UNIQUE,
    quantity          INTEGER     NOT NULL CHECK (quantity >= 0),
    reserved_quantity INTEGER     NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
    harvest_date      TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE,
    updated_at        TIMESTAMP WITH TIME ZONE
);

-- 3. Tạo Index để tìm kiếm nhanh theo product_id (Dù UNIQUE đã có index ngầm định, nhưng khai báo rõ ràng vẫn tốt hơn)
CREATE INDEX idx_inventory_product_id ON inventory_service.inventories (product_id);